### ISSUE TITLE
Identifier '__global__ has already been declared

### ISSUE THREAD

**Issue by hanakin** [xojs/atom-linter-xo#98] opened 2019-05-25 02:15 UTC
I get this error in atom when saving a js file using version 0.24.0 in my pkg.json

**Comment by hanakin** [comment] 2019-06-02 23:44
bump still having this error...

**Comment by pvdlg** [comment] 2019-06-05 21:45
This is caused by https://github.com/standard-things/esm/issues/816

**Comment by sindresorhus** [comment] 2023-06-20 23:22
Closing as Atom is abandoned.

**Closed by sindresorhus** 2023-06-20 23:22 UTC
